services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # HTTP로 접속하면 자동으로 HTTPS로 강제 이동 (Vercel 통신 필수 설정)
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      # 인증서 발급용 이메일 주소 반영
      - "--certificatesresolvers.myresolver.acme.email=wnswp1122@naver.com" 
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  backend:
    image: ${ECR_REPOSITORY}:${IMAGE_TAG}
    container_name: backend
    env_file:
      - .env.prod
    restart: always
    labels:
      - "traefik.enable=true"
      # 본인의 DuckDNS 도메인 주소
      - "traefik.http.routers.backend.rule=Host(`law-loading-api.duckdns.org`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    command: >
      bash -c "
      python manage.py collectstatic --no-input &&
      python manage.py migrate &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "
